name: Get file and convert
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: convert notebooks and word docs to posts
        uses: fastai/fastpages@master
      - name: Jekyll build
        uses: docker://jekyll/jekyll
        with:
          args: jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #external_repository: username/external-repository
          #publish_branch: gh-pages
          publish_dir: ./_site